//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pluralsight-original")]
        public string OriginalBucketName {
            get {
                return ((string)(this["OriginalBucketName"]));
            }
            set {
                this["OriginalBucketName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://s3-ap-southeast-2.amazonaws.com/pluralsight-original/")]
        public string OriginalBucketUrl {
            get {
                return ((string)(this["OriginalBucketUrl"]));
            }
            set {
                this["OriginalBucketUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pluralsight-resized")]
        public string ResizedBucketName {
            get {
                return ((string)(this["ResizedBucketName"]));
            }
            set {
                this["ResizedBucketName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://s3-ap-southeast-2.amazonaws.com/pluralsight-resized/")]
        public string ResizedBucketUrl {
            get {
                return ((string)(this["ResizedBucketUrl"]));
            }
            set {
                this["ResizedBucketUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pluralsight-original")]
        public string VaultName {
            get {
                return ((string)(this["VaultName"]));
            }
            set {
                this["VaultName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ap-southeast-2")]
        public string AWSRegion {
            get {
                return ((string)(this["AWSRegion"]));
            }
            set {
                this["AWSRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AKIAIANO4HFUOBGNGU7Q")]
        public string AWSAccessKey {
            get {
                return ((string)(this["AWSAccessKey"]));
            }
            set {
                this["AWSAccessKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X0WIMQkfsoISeZrw5I3LtCLw0GGy8fcl8wR3qxnO")]
        public string AWSSecretKey {
            get {
                return ((string)(this["AWSSecretKey"]));
            }
            set {
                this["AWSSecretKey"] = value;
            }
        }
    }
}
